name = "whatsapp-alpaca-bot"
main = "index.js"
compatibility_date = "2024-12-18"


# Place environment secrets in Cloudflare Dashboard or set via `wrangler secret put <KEY>`
# [vars]
# ALPACA_KEY_ID = (Your Alpaca key)
# ALPACA_SECRET_KEY = (Your Alpaca secret)
# ALPACA_PAPER_TRADING = "true"

[[kv_namespaces]]
binding = "USER_SESSIONS"
id = "b7261f8c0f2b4b098d96b5cbf787cf77"

